---
abstract: 'method and function declarations with signatures and no source filter'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  Module::Build: '0.26'
  Test::Builder: '0.82'
  Test::Exception: '0.29'
  Test::More: '0.82'
  Test::Warn: '0.10'
configure_requires:
  Module::Build: '0.31'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Method-Signatures
provides:
  Method::Signatures:
    file: lib/Method/Signatures.pm
    version: 20160608.0051_002
  Method::Signatures::Modifiers:
    file: lib/Method/Signatures/Modifiers.pm
    version: 20160608.0051_002
  Method::Signatures::Parameter:
    file: lib/Method/Signatures/Parameter.pm
  Method::Signatures::Signature:
    file: lib/Method/Signatures/Signature.pm
  Method::Signatures::Types:
    file: lib/Method/Signatures/Types.pm
  Method::Signatures::Utils:
    file: lib/Method/Signatures/Utils.pm
recommends:
  Data::Alias: '1.08'
  Moose: '0.96'
requires:
  Any::Moose: '0.11'
  Const::Fast: '0.006'
  Devel::Declare: '0.006002'
  Devel::Declare::MethodInstaller::Simple: '0.006002'
  Lexical::SealRequireHints: '0.008'
  Mouse: '0.64'
  PPI: '1.203'
  Sub::Name: '0.03'
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Method-Signatures
  license: http://dev.perl.org/licenses/
  repository: https://github.com/evalEmpire/method-signatures
version: 20160608.0051_002
